-- Initial PostgreSQL schema for Project Report Assistant.
-- IDs using Prisma `cuid()` are generated by Prisma Client.

CREATE TABLE "Project" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "preparedBy" TEXT,
    "structureType" TEXT NOT NULL DEFAULT 'House',
    "scopeType" TEXT NOT NULL DEFAULT 'FullRemodel',
    "thisWeekStart" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Project_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Task" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "taskName" TEXT NOT NULL,
    "phase" TEXT,
    "trade" TEXT,
    "ownerCompany" TEXT NOT NULL,
    "durationDays" INTEGER NOT NULL,
    "requiresInspection" BOOLEAN NOT NULL DEFAULT false,
    "callNow" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Task_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Dependency" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "fromTaskId" TEXT NOT NULL,
    "toTaskId" TEXT NOT NULL,

    CONSTRAINT "Dependency_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "TaskStatus" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "confirmedComplete" BOOLEAN NOT NULL DEFAULT false,
    "inspectionRequired" BOOLEAN NOT NULL DEFAULT false,
    "inspectionPassed" BOOLEAN NOT NULL DEFAULT false,
    "lastUpdated" TIMESTAMP(3),

    CONSTRAINT "TaskStatus_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Company" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,

    CONSTRAINT "Company_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Trade" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,

    CONSTRAINT "Trade_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "CompanyTradeMap" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "tradeId" TEXT NOT NULL,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,

    CONSTRAINT "CompanyTradeMap_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Contact" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "phone" TEXT,
    "email" TEXT,
    "role" TEXT,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "Contact_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "LookaheadEntry" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "symbol" TEXT NOT NULL,
    "notes" TEXT,

    CONSTRAINT "LookaheadEntry_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "VersionLog" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "runType" TEXT NOT NULL,
    "countsJson" JSONB,

    CONSTRAINT "VersionLog_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Task_projectId_taskId_key" ON "Task"("projectId", "taskId");
CREATE INDEX "Task_projectId_phase_idx" ON "Task"("projectId", "phase");
CREATE INDEX "Task_projectId_trade_idx" ON "Task"("projectId", "trade");

CREATE UNIQUE INDEX "Dependency_projectId_fromTaskId_toTaskId_key" ON "Dependency"("projectId", "fromTaskId", "toTaskId");
CREATE INDEX "Dependency_projectId_toTaskId_idx" ON "Dependency"("projectId", "toTaskId");

CREATE UNIQUE INDEX "TaskStatus_projectId_taskId_key" ON "TaskStatus"("projectId", "taskId");

CREATE UNIQUE INDEX "Company_name_key" ON "Company"("name");

CREATE UNIQUE INDEX "Trade_name_key" ON "Trade"("name");

CREATE UNIQUE INDEX "CompanyTradeMap_companyId_tradeId_key" ON "CompanyTradeMap"("companyId", "tradeId");
CREATE INDEX "CompanyTradeMap_tradeId_idx" ON "CompanyTradeMap"("tradeId");

CREATE INDEX "Contact_companyId_idx" ON "Contact"("companyId");

CREATE UNIQUE INDEX "LookaheadEntry_projectId_taskId_date_key" ON "LookaheadEntry"("projectId", "taskId", "date");
CREATE INDEX "LookaheadEntry_projectId_date_idx" ON "LookaheadEntry"("projectId", "date");
CREATE INDEX "VersionLog_projectId_timestamp_idx" ON "VersionLog"("projectId", "timestamp");

ALTER TABLE "Task" ADD CONSTRAINT "Task_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Dependency" ADD CONSTRAINT "Dependency_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TaskStatus" ADD CONSTRAINT "TaskStatus_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CompanyTradeMap" ADD CONSTRAINT "CompanyTradeMap_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CompanyTradeMap" ADD CONSTRAINT "CompanyTradeMap_tradeId_fkey" FOREIGN KEY ("tradeId") REFERENCES "Trade"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Contact" ADD CONSTRAINT "Contact_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LookaheadEntry" ADD CONSTRAINT "LookaheadEntry_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "VersionLog" ADD CONSTRAINT "VersionLog_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
